export const FETCH_NOTES = '@@notes/FETCH'
export const SUCCESS_NOTES = '@@notes/SUCCESS'
export const FAILURE_NOTES = '@@notes/FAILURE'
export const SELECT_NOTE = '@@notes/SELECT'
export const ADD_COLOR_FILTER = '@@filters/ADD'
export const DELETE_COLOR_FILTER = '@@filters/DELETE'
