export const FETCH_NOTES = '@@Notes/FETCH'
export const SUCCESS_NOTES = '@@Notes/SUCCESS'
export const FAILURE_NOTES = '@@Notes/FAILURE'
export const SELECT_NOTE = '@@Notes/SELECT'
export const ADD_COLOR_FILTER = '@@filters/ADD'
export const DELETE_COLOR_FILTER = '@@filters/DELETE'
